[workspace]
authors = ["pyramidheadshark <pyramidheadshark@gmail.com>"]
channels = ["conda-forge"]
name = "internship-practice"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"

[pypi-dependencies]
numpy = ">=2.2.4, <3"
pandas = ">=2.2.3, <3"
networkx = ">=3.4.2, <4"
ipykernel = ">=6.29.5, <7"
jupyter = ">=1.1.1, <2"
